use anyhow::{Context, Result};
use colored::Colorize;
use std::fs;
use std::path::PathBuf;

/// Help text shown in `loadout completions --help`.
pub const AFTER_HELP: &str = r#"SETUP:

  zsh (recommended — add to fpath):
    mkdir -p ~/.zfunc
    loadout completions zsh > ~/.zfunc/_loadout

    # Add to ~/.zshrc BEFORE compinit:
    fpath=(~/.zfunc $fpath)
    autoload -Uz compinit && compinit

  zsh (oh-my-zsh):
    mkdir -p ~/.oh-my-zsh/completions
    loadout completions zsh > ~/.oh-my-zsh/completions/_loadout

  zsh (inline eval — slower, runs on every shell start):
    # Add to ~/.zshrc:
    eval "$(loadout completions zsh)"

  bash (bash-completion — recommended):
    mkdir -p ~/.local/share/bash-completion/completions
    loadout completions bash > ~/.local/share/bash-completion/completions/loadout

  bash (inline eval):
    # Add to ~/.bashrc:
    eval "$(loadout completions bash)"

  fish:
    loadout completions fish > ~/.config/fish/completions/loadout.fish

  Auto-install (writes to the standard location for your shell):
    loadout completions zsh --install
    loadout completions bash --install
    loadout completions fish --install"#;

pub const ZSH_SCRIPT: &str = r#"#compdef loadout

# Loadout — agent skill manager
# Generated by: loadout completions zsh

_loadout_sources() {
    local -a sources
    sources=(${(f)"$(loadout _complete sources 2>/dev/null)"})
    [[ ${#sources} -gt 0 ]] && _describe 'source' sources
}

_loadout_agents() {
    local -a targets
    targets=(${(f)"$(loadout _complete agents 2>/dev/null)"})
    [[ ${#targets} -gt 0 ]] && _describe 'agent' agents
}

_loadout_skills() {
    local -a skills
    skills=(${(f)"$(loadout _complete skills 2>/dev/null)"})
    [[ ${#skills} -gt 0 ]] && compadd -a skills
}

_loadout_plugins() {
    local -a plugins
    plugins=(${(f)"$(loadout _complete plugins 2>/dev/null)"})
    [[ ${#plugins} -gt 0 ]] && compadd -a plugins
}

_loadout_kits() {
    local -a kits
    kits=(${(f)"$(loadout _complete kits 2>/dev/null)"})
    [[ ${#kits} -gt 0 ]] && _describe 'kit' kits
}

_loadout() {
    local -a global_flags
    global_flags=(
        '(-n --dry-run)'{-n,--dry-run}'[Preview changes without writing]'
        '(-v --verbose)'{-v,--verbose}'[Show detailed output]'
        '(-q --quiet)'{-q,--quiet}'[Suppress output]'
        '--json[Output as JSON]'
        '--config[Override config file path]:config file:_files'
        '(-h --help)'{-h,--help}'[Show help]'
        '--version[Show version]'
    )

    _arguments -C \
        $global_flags \
        '1:command:->commands' \
        '*::arg:->args'

    case $state in
    commands)
        local -a commands
        commands=(
            'init:Initialize loadout configuration'
            'add:Add a skill source'
            'list:List skills or sources'
            'remove:Remove a skill source'
            'update:Update sources from remote'
            'status:Show current install state'
            'kit:Manage skill kits'
            'agent:Manage agents'
            'config:View or edit configuration'
            'completions:Generate shell completions'
        )
        _describe 'command' commands
        ;;
    args)
        case $words[1] in
        init)
            _arguments $global_flags \
                '1::url:'
            ;;
        add)
            _arguments $global_flags \
                '--source[Override source name]:name:' \
                '--plugin[Override plugin name]:name:' \
                '--skill[Override skill name]:name:' \
                '--ref[Pin to git ref]:ref:' \
                '(--copy)--symlink[Symlink local source]' \
                '(--symlink)--copy[Copy local source]' \
                '1:url:_urls'
            ;;
        list)
            _arguments $global_flags \
                '--external[List sources instead of skills]' \
                '*:pattern:'
            ;;
        remove)
            _arguments $global_flags \
                '--force[Force removal even if installed]' \
                '1::source:_loadout_sources'
            ;;
        update)
            _arguments $global_flags \
                '--ref[Switch to ref or "latest" to unpin]:ref:' \
                '1::source:_loadout_sources'
            ;;
        status)
            _arguments $global_flags
            ;;
        kit)
            local -a kit_commands
            _arguments -C $global_flags \
                '1:subcommand:->kit_cmds' \
                '*::arg:->kit_args'
            case $state in
            kit_cmds)
                kit_commands=(
                    'create:Create a new kit'
                    'delete:Delete a kit'
                    'list:List kits'
                    'show:Show kit details'
                    'add:Add skills to a kit'
                    'drop:Remove skills from a kit'
                )
                _describe 'kit command' kit_commands
                ;;
            kit_args)
                case $words[1] in
                create)
                    _arguments '1:name:'
                    ;;
                delete)
                    _arguments \
                        '--force[Force delete active kit]' \
                        '1:kit:_loadout_kits'
                    ;;
                list)
                    _arguments '*:pattern:'
                    ;;
                show)
                    _arguments '1:kit:_loadout_kits'
                    ;;
                add)
                    _arguments \
                        '1:kit:_loadout_kits' \
                        '*:skill:_loadout_skills'
                    ;;
                drop)
                    _arguments \
                        '1:kit:_loadout_kits' \
                        '*:skill:_loadout_skills'
                    ;;
                esac
                ;;
            esac
            ;;
        agent)
            local -a agent_commands
            _arguments -C $global_flags \
                '1:subcommand:->agent_cmds' \
                '*::arg:->agent_args'
            case $state in
            agent_cmds)
                agent_commands=(
                    'add:Register a new agent'
                    'remove:Unregister an agent'
                    'list:Show all agents'
                    'show:Show agent details'
                    'detect:Auto-discover agent installations'
                    'equip:Equip skills to agents'
                    'unequip:Unequip skills from agents'
                    'collect:Collect edited skills back from agent'
                )
                _describe 'agent command' agent_commands
                ;;
            agent_args)
                case $words[1] in
                add)
                    _arguments \
                        '--name[Agent name]:name:' \
                        '--scope[Agent scope]:scope:(machine repo)' \
                        '--sync[Sync mode]:sync:(auto explicit)' \
                        '1:agent:(claude codex cursor)' \
                        '2::path:_directories'
                    ;;
                remove)
                    _arguments \
                        '--force[Required for removal]' \
                        '1:agent:_loadout_agents'
                    ;;
                show)
                    _arguments '1:agent:_loadout_agents'
                    ;;
                list)
                    ;;
                detect)
                    _arguments '--force[Auto-add discovered agents]'
                    ;;
                equip)
                    _arguments \
                        '*'{-a,--agent}'[Agent to equip]:agent:_loadout_agents' \
                        '--all[All configured skills]' \
                        '(-k --kit)'{-k,--kit}'[Kit to equip]:kit:_loadout_kits' \
                        '(-s --save-kit)'{-s,--save-kit}'[Save selection as kit]:name:' \
                        '(-f --force)'{-f,--force}'[Overwrite without prompting]' \
                        '(-i --interactive)'{-i,--interactive}'[Interactive conflict resolution]' \
                        '*:pattern:_loadout_skills'
                    ;;
                unequip)
                    _arguments \
                        '*'{-a,--agent}'[Agent to unequip]:agent:_loadout_agents' \
                        '--all[All equipped skills]' \
                        '(-k --kit)'{-k,--kit}'[Kit to unequip]:kit:_loadout_kits' \
                        '(-f --force)'{-f,--force}'[Force unequip]' \
                        '*:pattern:_loadout_skills'
                    ;;
                collect)
                    _arguments \
                        '--agent[Agent to collect from]:agent:_loadout_agents' \
                        '--skill[Specific skill]:skill:_loadout_skills' \
                        '--adopt[Adopt into plugins/]' \
                        '--force[Auto-adopt all without prompting]'
                    ;;
                esac
                ;;
            esac
            ;;
        config)
            local -a config_commands
            _arguments -C $global_flags \
                '1:subcommand:->config_cmds'
            case $state in
            config_cmds)
                config_commands=(
                    'show:Display configuration'
                    'edit:Open configuration in editor'
                )
                _describe 'config command' config_commands
                ;;
            esac
            ;;
        completions)
            _arguments \
                '--install[Install completions to shell config]' \
                '1:shell:(bash zsh fish)'
            ;;
        esac
        ;;
    esac
}

_loadout "$@"
"#;

pub const BASH_SCRIPT: &str = r#"# Loadout — agent skill manager
# Generated by: loadout completions bash

_loadout_sources() {
    loadout _complete sources 2>/dev/null
}

_loadout_agents() {
    loadout _complete agents 2>/dev/null
}

_loadout_skills() {
    loadout _complete skills 2>/dev/null
}

_loadout_plugins() {
    loadout _complete plugins 2>/dev/null
}

_loadout_kits() {
    loadout _complete kits 2>/dev/null
}

_loadout() {
    local cur prev words cword
    _init_completion || return

    local commands="init add list remove update status kit agent config completions"
    local global_flags="--dry-run -n --verbose -v --quiet -q --json --config --help -h --version"

    # Find the primary command (first non-flag arg after 'loadout')
    local cmd="" cmd_idx=0
    for ((i=1; i < cword; i++)); do
        case "${words[i]}" in
            -*) continue ;;
            *)
                if [[ -z "$cmd" ]]; then
                    cmd="${words[i]}"
                    cmd_idx=$i
                fi
                ;;
        esac
    done

    # No command yet — complete command names or global flags
    if [[ -z "$cmd" ]]; then
        if [[ "$cur" == -* ]]; then
            COMPREPLY=($(compgen -W "$global_flags" -- "$cur"))
        else
            COMPREPLY=($(compgen -W "$commands" -- "$cur"))
        fi
        return
    fi

    # Find subcommand for kit/agent/config
    local subcmd=""
    if [[ "$cmd" == "kit" || "$cmd" == "agent" || "$cmd" == "config" ]]; then
        for ((i=cmd_idx+1; i < cword; i++)); do
            case "${words[i]}" in
                -*) continue ;;
                *)
                    if [[ -z "$subcmd" ]]; then
                        subcmd="${words[i]}"
                    fi
                    ;;
            esac
        done
    fi

    case "$cmd" in
    init)
        [[ "$cur" == -* ]] && COMPREPLY=($(compgen -W "$global_flags" -- "$cur"))
        ;;
    add)
        if [[ "$cur" == -* ]]; then
            COMPREPLY=($(compgen -W "$global_flags --source --plugin --skill --ref --symlink --copy" -- "$cur"))
        fi
        ;;
    list)
        if [[ "$cur" == -* ]]; then
            COMPREPLY=($(compgen -W "$global_flags --external" -- "$cur"))
        fi
        ;;
    remove)
        if [[ "$cur" == -* ]]; then
            COMPREPLY=($(compgen -W "$global_flags --force" -- "$cur"))
        else
            COMPREPLY=($(compgen -W "$(_loadout_sources)" -- "$cur"))
        fi
        ;;
    update)
        case "$prev" in
            --ref) ;;
            *)
                if [[ "$cur" == -* ]]; then
                    COMPREPLY=($(compgen -W "$global_flags --ref" -- "$cur"))
                else
                    COMPREPLY=($(compgen -W "$(_loadout_sources)" -- "$cur"))
                fi
                ;;
        esac
        ;;
    status)
        [[ "$cur" == -* ]] && COMPREPLY=($(compgen -W "$global_flags" -- "$cur"))
        ;;
    kit)
        if [[ -z "$subcmd" ]]; then
            if [[ "$cur" == -* ]]; then
                COMPREPLY=($(compgen -W "$global_flags" -- "$cur"))
            else
                COMPREPLY=($(compgen -W "create delete list show add drop" -- "$cur"))
            fi
        else
            case "$subcmd" in
            create)
                ;;
            delete)
                if [[ "$cur" == -* ]]; then
                    COMPREPLY=($(compgen -W "--force" -- "$cur"))
                else
                    COMPREPLY=($(compgen -W "$(_loadout_kits)" -- "$cur"))
                fi
                ;;
            show)
                [[ "$cur" != -* ]] && COMPREPLY=($(compgen -W "$(_loadout_kits)" -- "$cur"))
                ;;
            list)
                ;;
            add|drop)
                # First arg after subcmd is kit name, rest are skills
                local args_after=0
                for ((i=cmd_idx+1; i < cword; i++)); do
                    case "${words[i]}" in
                        "$subcmd"|--*) continue ;;
                        *) ((args_after++)) ;;
                    esac
                done
                if [[ $args_after -eq 0 ]]; then
                    COMPREPLY=($(compgen -W "$(_loadout_kits)" -- "$cur"))
                else
                    COMPREPLY=($(compgen -W "$(_loadout_skills)" -- "$cur"))
                fi
                ;;
            esac
        fi
        ;;
    agent)
        if [[ -z "$subcmd" ]]; then
            if [[ "$cur" == -* ]]; then
                COMPREPLY=($(compgen -W "$global_flags" -- "$cur"))
            else
                COMPREPLY=($(compgen -W "add remove list show detect equip unequip collect" -- "$cur"))
            fi
        else
            case "$subcmd" in
            add)
                case "$prev" in
                    --name) ;;
                    --scope) COMPREPLY=($(compgen -W "machine repo" -- "$cur")) ;;
                    --sync) COMPREPLY=($(compgen -W "auto explicit" -- "$cur")) ;;
                    *)
                        if [[ "$cur" == -* ]]; then
                            COMPREPLY=($(compgen -W "--name --scope --sync" -- "$cur"))
                        else
                            COMPREPLY=($(compgen -W "claude codex cursor" -- "$cur"))
                        fi
                        ;;
                esac
                ;;
            remove)
                if [[ "$cur" == -* ]]; then
                    COMPREPLY=($(compgen -W "--force" -- "$cur"))
                else
                    COMPREPLY=($(compgen -W "$(_loadout_agents)" -- "$cur"))
                fi
                ;;
            show)
                COMPREPLY=($(compgen -W "$(_loadout_agents)" -- "$cur"))
                ;;
            detect)
                [[ "$cur" == -* ]] && COMPREPLY=($(compgen -W "--force" -- "$cur"))
                ;;
            equip)
                case "$prev" in
                    -a|--agent) COMPREPLY=($(compgen -W "$(_loadout_agents)" -- "$cur")) ;;
                    -k|--kit) COMPREPLY=($(compgen -W "$(_loadout_kits)" -- "$cur")) ;;
                    -s|--save-kit) ;;
                    *)
                        if [[ "$cur" == -* ]]; then
                            COMPREPLY=($(compgen -W "--agent -a --all --kit -k --save-kit -s --force -f --interactive -i" -- "$cur"))
                        else
                            COMPREPLY=($(compgen -W "$(_loadout_skills)" -- "$cur"))
                        fi
                        ;;
                esac
                ;;
            unequip)
                case "$prev" in
                    -a|--agent) COMPREPLY=($(compgen -W "$(_loadout_agents)" -- "$cur")) ;;
                    -k|--kit) COMPREPLY=($(compgen -W "$(_loadout_kits)" -- "$cur")) ;;
                    *)
                        if [[ "$cur" == -* ]]; then
                            COMPREPLY=($(compgen -W "--agent -a --all --kit -k --force -f" -- "$cur"))
                        else
                            COMPREPLY=($(compgen -W "$(_loadout_skills)" -- "$cur"))
                        fi
                        ;;
                esac
                ;;
            collect)
                case "$prev" in
                    --skill) COMPREPLY=($(compgen -W "$(_loadout_skills)" -- "$cur")) ;;
                    --agent) COMPREPLY=($(compgen -W "$(_loadout_agents)" -- "$cur")) ;;
                    *)
                        [[ "$cur" == -* ]] && COMPREPLY=($(compgen -W "--agent --skill --adopt --force" -- "$cur"))
                        ;;
                esac
                ;;
            esac
        fi
        ;;
    config)
        if [[ -z "$subcmd" ]]; then
            COMPREPLY=($(compgen -W "show edit" -- "$cur"))
        fi
        ;;
    completions)
        if [[ "$cur" == -* ]]; then
            COMPREPLY=($(compgen -W "--install" -- "$cur"))
        else
            COMPREPLY=($(compgen -W "bash zsh fish" -- "$cur"))
        fi
        ;;
    esac
}

complete -o default -F _loadout loadout
"#;

pub const FISH_SCRIPT: &str = r#"# Loadout — agent skill manager
# Generated by: loadout completions fish

# Helpers for dynamic completions
function __loadout_sources
    loadout _complete sources 2>/dev/null
end

function __loadout_agents
    loadout _complete agents 2>/dev/null
end

function __loadout_skills
    loadout _complete skills 2>/dev/null
end

function __loadout_plugins
    loadout _complete plugins 2>/dev/null
end

function __loadout_kits
    loadout _complete kits 2>/dev/null
end

function __loadout_needs_command
    set -l cmd (commandline -opc)
    test (count $cmd) -eq 1
end

function __loadout_using_command
    set -l cmd (commandline -opc)
    test (count $cmd) -gt 1; and test "$cmd[2]" = "$argv[1]"
end

function __loadout_using_subcommand
    set -l cmd (commandline -opc)
    test (count $cmd) -gt 2; and test "$cmd[2]" = "$argv[1]"; and test "$cmd[3]" = "$argv[2]"
end

# Global flags
complete -c loadout -l dry-run -s n -d 'Preview changes without writing'
complete -c loadout -l verbose -s v -d 'Show detailed output'
complete -c loadout -l quiet -s q -d 'Suppress output'
complete -c loadout -l json -d 'Output as JSON'
complete -c loadout -l config -r -d 'Override config file path'
complete -c loadout -l help -s h -d 'Show help'
complete -c loadout -l version -d 'Show version'

# Top-level commands
complete -c loadout -f -n __loadout_needs_command -a init -d 'Initialize loadout configuration'
complete -c loadout -f -n __loadout_needs_command -a add -d 'Add a skill source'
complete -c loadout -f -n __loadout_needs_command -a list -d 'List skills or sources'
complete -c loadout -f -n __loadout_needs_command -a remove -d 'Remove a skill source'
complete -c loadout -f -n __loadout_needs_command -a update -d 'Update sources from remote'
complete -c loadout -f -n __loadout_needs_command -a status -d 'Show current install state'
complete -c loadout -f -n __loadout_needs_command -a kit -d 'Manage skill kits'
complete -c loadout -f -n __loadout_needs_command -a agent -d 'Manage agents'
complete -c loadout -f -n __loadout_needs_command -a config -d 'View or edit configuration'
complete -c loadout -f -n __loadout_needs_command -a completions -d 'Generate shell completions'

# add
complete -c loadout -f -n '__loadout_using_command add' -l source -r -d 'Override source name'
complete -c loadout -f -n '__loadout_using_command add' -l plugin -r -d 'Override plugin name'
complete -c loadout -f -n '__loadout_using_command add' -l skill -r -d 'Override skill name'
complete -c loadout -f -n '__loadout_using_command add' -l ref -r -d 'Pin to git ref'
complete -c loadout -f -n '__loadout_using_command add' -l symlink -d 'Symlink local source'
complete -c loadout -f -n '__loadout_using_command add' -l copy -d 'Copy local source'

# list
complete -c loadout -f -n '__loadout_using_command list' -l external -d 'List sources instead'

# remove
complete -c loadout -f -n '__loadout_using_command remove' -l force -d 'Force removal'
complete -c loadout -f -n '__loadout_using_command remove' -a '(__loadout_sources)'

# update
complete -c loadout -f -n '__loadout_using_command update' -l ref -r -d 'Switch to ref'
complete -c loadout -f -n '__loadout_using_command update' -a '(__loadout_sources)'

# kit subcommands
complete -c loadout -f -n '__loadout_using_command kit' -a create -d 'Create a new kit'
complete -c loadout -f -n '__loadout_using_command kit' -a delete -d 'Delete a kit'
complete -c loadout -f -n '__loadout_using_command kit' -a list -d 'List kits'
complete -c loadout -f -n '__loadout_using_command kit' -a show -d 'Show kit details'
complete -c loadout -f -n '__loadout_using_command kit' -a add -d 'Add skills to a kit'
complete -c loadout -f -n '__loadout_using_command kit' -a drop -d 'Remove skills from a kit'

complete -c loadout -f -n '__loadout_using_subcommand kit delete' -l force -d 'Force delete'
complete -c loadout -f -n '__loadout_using_subcommand kit delete' -a '(__loadout_kits)'
complete -c loadout -f -n '__loadout_using_subcommand kit show' -a '(__loadout_kits)'
complete -c loadout -f -n '__loadout_using_subcommand kit add' -a '(__loadout_kits) (__loadout_skills)'
complete -c loadout -f -n '__loadout_using_subcommand kit drop' -a '(__loadout_kits) (__loadout_skills)'

# agent subcommands
complete -c loadout -f -n '__loadout_using_command agent' -a add -d 'Register a new agent'
complete -c loadout -f -n '__loadout_using_command agent' -a remove -d 'Unregister an agent'
complete -c loadout -f -n '__loadout_using_command agent' -a list -d 'Show all agents'
complete -c loadout -f -n '__loadout_using_command agent' -a show -d 'Show agent details'
complete -c loadout -f -n '__loadout_using_command agent' -a detect -d 'Auto-discover agents'
complete -c loadout -f -n '__loadout_using_command agent' -a equip -d 'Equip skills to agents'
complete -c loadout -f -n '__loadout_using_command agent' -a unequip -d 'Unequip skills from agents'
complete -c loadout -f -n '__loadout_using_command agent' -a collect -d 'Collect edited skills back'

complete -c loadout -f -n '__loadout_using_subcommand agent add' -l name -r -d 'Agent name'
complete -c loadout -f -n '__loadout_using_subcommand agent add' -l scope -r -a 'machine repo' -d 'Scope'
complete -c loadout -f -n '__loadout_using_subcommand agent add' -l sync -r -a 'auto explicit' -d 'Sync mode'
complete -c loadout -f -n '__loadout_using_subcommand agent add' -a 'claude codex cursor'
complete -c loadout -f -n '__loadout_using_subcommand agent remove' -l force -d 'Required for removal'
complete -c loadout -f -n '__loadout_using_subcommand agent remove' -a '(__loadout_agents)'
complete -c loadout -f -n '__loadout_using_subcommand agent show' -a '(__loadout_agents)'
complete -c loadout -f -n '__loadout_using_subcommand agent detect' -l force -d 'Auto-add'
complete -c loadout -f -n '__loadout_using_subcommand agent equip' -l agent -s a -r -a '(__loadout_agents)' -d 'Agent'
complete -c loadout -f -n '__loadout_using_subcommand agent equip' -l all -d 'All configured skills'
complete -c loadout -f -n '__loadout_using_subcommand agent equip' -l kit -s k -r -a '(__loadout_kits)' -d 'Kit to equip'
complete -c loadout -f -n '__loadout_using_subcommand agent equip' -l save-kit -s s -r -d 'Save selection as kit'
complete -c loadout -f -n '__loadout_using_subcommand agent equip' -l force -s f -d 'Overwrite without prompting'
complete -c loadout -f -n '__loadout_using_subcommand agent equip' -l interactive -s i -d 'Interactive conflict resolution'
complete -c loadout -f -n '__loadout_using_subcommand agent equip' -a '(__loadout_skills)'
complete -c loadout -f -n '__loadout_using_subcommand agent unequip' -l agent -s a -r -a '(__loadout_agents)' -d 'Agent'
complete -c loadout -f -n '__loadout_using_subcommand agent unequip' -l all -d 'All equipped skills'
complete -c loadout -f -n '__loadout_using_subcommand agent unequip' -l kit -s k -r -a '(__loadout_kits)' -d 'Kit to unequip'
complete -c loadout -f -n '__loadout_using_subcommand agent unequip' -l force -s f -d 'Force unequip'
complete -c loadout -f -n '__loadout_using_subcommand agent unequip' -a '(__loadout_skills)'
complete -c loadout -f -n '__loadout_using_subcommand agent collect' -l agent -r -a '(__loadout_agents)' -d 'Agent'
complete -c loadout -f -n '__loadout_using_subcommand agent collect' -l skill -r -a '(__loadout_skills)' -d 'Specific skill'
complete -c loadout -f -n '__loadout_using_subcommand agent collect' -l adopt -d 'Adopt into plugins/'
complete -c loadout -f -n '__loadout_using_subcommand agent collect' -l force -d 'Auto-adopt all'

# config subcommands
complete -c loadout -f -n '__loadout_using_command config' -a show -d 'Display configuration'
complete -c loadout -f -n '__loadout_using_command config' -a edit -d 'Open in editor'

# completions
complete -c loadout -f -n '__loadout_using_command completions' -l install -d 'Install to shell config'
complete -c loadout -f -n '__loadout_using_command completions' -a 'bash zsh fish'
"#;

/// Install completions for zsh.
pub fn install_zsh(quiet: bool) -> Result<PathBuf> {
    let home = dirs::home_dir().context("cannot determine home directory")?;

    // Prefer oh-my-zsh completions dir if it exists
    let omz_dir = home.join(".oh-my-zsh/completions");
    let (dest, extra) = if omz_dir.is_dir() {
        (omz_dir.join("_loadout"), None)
    } else {
        let zfunc = home.join(".zfunc");
        fs::create_dir_all(&zfunc)
            .with_context(|| format!("failed to create {}", zfunc.display()))?;

        let needs_fpath = {
            let zshrc = home.join(".zshrc");
            if let Ok(content) = fs::read_to_string(&zshrc) {
                !content.contains(".zfunc")
            } else {
                true
            }
        };

        let hint = if needs_fpath {
            Some(format!(
                "\n{}  Add to {} (before compinit):\n\n    {}\n    {}",
                "Note:".yellow().bold(),
                "~/.zshrc".bold(),
                "fpath=(~/.zfunc $fpath)",
                "autoload -Uz compinit && compinit",
            ))
        } else {
            None
        };

        (zfunc.join("_loadout"), hint)
    };

    fs::write(&dest, ZSH_SCRIPT)
        .with_context(|| format!("failed to write {}", dest.display()))?;

    if !quiet {
        println!(
            "{} Installed zsh completions to {}",
            "✓".green(),
            dest.display().to_string().bold()
        );
        if let Some(hint) = extra {
            println!("{}", hint);
        }
        println!("\nRestart your shell or run: {}", "exec zsh".bold());
    }

    Ok(dest)
}

/// Install completions for bash.
pub fn install_bash(quiet: bool) -> Result<PathBuf> {
    let home = dirs::home_dir().context("cannot determine home directory")?;
    let comp_dir = home.join(".local/share/bash-completion/completions");
    fs::create_dir_all(&comp_dir)
        .with_context(|| format!("failed to create {}", comp_dir.display()))?;

    let dest = comp_dir.join("loadout");
    fs::write(&dest, BASH_SCRIPT)
        .with_context(|| format!("failed to write {}", dest.display()))?;

    if !quiet {
        println!(
            "{} Installed bash completions to {}",
            "✓".green(),
            dest.display().to_string().bold()
        );
        println!(
            "\nRestart your shell or run: {}",
            format!("source {}", dest.display()).bold()
        );
    }

    Ok(dest)
}

/// Install completions for fish.
pub fn install_fish(quiet: bool) -> Result<PathBuf> {
    let home = dirs::home_dir().context("cannot determine home directory")?;
    let comp_dir = home.join(".config/fish/completions");
    fs::create_dir_all(&comp_dir)
        .with_context(|| format!("failed to create {}", comp_dir.display()))?;

    let dest = comp_dir.join("loadout.fish");
    fs::write(&dest, FISH_SCRIPT)
        .with_context(|| format!("failed to write {}", dest.display()))?;

    if !quiet {
        println!(
            "{} Installed fish completions to {}",
            "✓".green(),
            dest.display().to_string().bold()
        );
        println!("\nCompletions are available in new fish sessions.");
    }

    Ok(dest)
}
