use anyhow::{Context, Result};
use colored::Colorize;
use std::fs;
use std::path::PathBuf;

/// Help text shown in `loadout completions --help`.
pub const AFTER_HELP: &str = r#"SETUP:

  zsh (recommended — add to fpath):
    mkdir -p ~/.zfunc
    loadout completions zsh > ~/.zfunc/_loadout

    # Add to ~/.zshrc BEFORE compinit:
    fpath=(~/.zfunc $fpath)
    autoload -Uz compinit && compinit

  zsh (oh-my-zsh):
    mkdir -p ~/.oh-my-zsh/completions
    loadout completions zsh > ~/.oh-my-zsh/completions/_loadout

  zsh (inline eval — slower, runs on every shell start):
    # Add to ~/.zshrc:
    eval "$(loadout completions zsh)"

  bash (bash-completion — recommended):
    mkdir -p ~/.local/share/bash-completion/completions
    loadout completions bash > ~/.local/share/bash-completion/completions/loadout

  bash (inline eval):
    # Add to ~/.bashrc:
    eval "$(loadout completions bash)"

  fish:
    loadout completions fish > ~/.config/fish/completions/loadout.fish

  Auto-install (writes to the standard location for your shell):
    loadout completions zsh --install
    loadout completions bash --install
    loadout completions fish --install"#;

pub const ZSH_SCRIPT: &str = r#"#compdef loadout

# Loadout — agent skill manager
# Generated by: loadout completions zsh

_loadout_sources() {
    local -a sources
    sources=(${(f)"$(loadout _complete sources 2>/dev/null)"})
    [[ ${#sources} -gt 0 ]] && _describe 'source' sources
}

_loadout_targets() {
    local -a targets
    targets=(${(f)"$(loadout _complete targets 2>/dev/null)"})
    [[ ${#targets} -gt 0 ]] && _describe 'target' targets
}

_loadout_skills() {
    local -a skills
    skills=(${(f)"$(loadout _complete skills 2>/dev/null)"})
    [[ ${#skills} -gt 0 ]] && compadd -a skills
}

_loadout_plugins() {
    local -a plugins
    plugins=(${(f)"$(loadout _complete plugins 2>/dev/null)"})
    [[ ${#plugins} -gt 0 ]] && compadd -a plugins
}

_loadout_bundles() {
    local -a bundles
    bundles=(${(f)"$(loadout _complete bundles 2>/dev/null)"})
    [[ ${#bundles} -gt 0 ]] && _describe 'bundle' bundles
}

_loadout() {
    local -a global_flags
    global_flags=(
        '(-n --dry-run)'{-n,--dry-run}'[Preview changes without writing]'
        '(-v --verbose)'{-v,--verbose}'[Show detailed output]'
        '(-q --quiet)'{-q,--quiet}'[Suppress output]'
        '--json[Output as JSON]'
        '--config[Override config file path]:config file:_files'
        '(-h --help)'{-h,--help}'[Show help]'
        '--version[Show version]'
    )

    _arguments -C \
        $global_flags \
        '1:command:->commands' \
        '*::arg:->args'

    case $state in
    commands)
        local -a commands
        commands=(
            'init:Initialize loadout configuration'
            'add:Add a skill source'
            'list:List skills or sources'
            'remove:Remove a skill source'
            'update:Update sources from remote'
            'apply:Apply skills to targets'
            'uninstall:Uninstall skills from targets'
            'collect:Collect edited skills back from target'
            'status:Show current install state'
            'bundle:Manage skill bundles'
            'target:Manage install targets'
            'config:View or edit configuration'
            'completions:Generate shell completions'
        )
        _describe 'command' commands
        ;;
    args)
        case $words[1] in
        init)
            _arguments $global_flags \
                '1::url:'
            ;;
        add)
            _arguments $global_flags \
                '--source[Override source name]:name:' \
                '--plugin[Override plugin name]:name:' \
                '--skill[Override skill name]:name:' \
                '--ref[Pin to git ref]:ref:' \
                '(--copy)--symlink[Symlink local source]' \
                '(--symlink)--copy[Copy local source]' \
                '1:url:_urls'
            ;;
        list)
            _arguments $global_flags \
                '--external[List sources instead of skills]' \
                '*:pattern:'
            ;;
        remove)
            _arguments $global_flags \
                '--force[Force removal even if installed]' \
                '1::source:_loadout_sources'
            ;;
        update)
            _arguments $global_flags \
                '--ref[Switch to ref or "latest" to unpin]:ref:' \
                '1::source:_loadout_sources'
            ;;
        apply)
            _arguments $global_flags \
                '--all[Apply all configured skills]' \
                '--skill[Specific skill]:skill:_loadout_skills' \
                '--plugin[All skills in plugin]:plugin:_loadout_plugins' \
                '--bundle[Specific bundle]:bundle:_loadout_bundles' \
                '--target[Target to apply to]:target:_loadout_targets' \
                '(-f --force)'{-f,--force}'[Overwrite without prompting]' \
                '(-i --interactive)'{-i,--interactive}'[Interactive conflict resolution]'
            ;;
        uninstall)
            _arguments $global_flags \
                '--skill[Specific skill]:skill:_loadout_skills' \
                '--plugin[All skills in plugin]:plugin:_loadout_plugins' \
                '--bundle[Specific bundle]:bundle:_loadout_bundles' \
                '--target[Target]:target:_loadout_targets' \
                '--force[Actually perform uninstall]'
            ;;
        collect)
            _arguments $global_flags \
                '--skill[Specific skill]:skill:_loadout_skills' \
                '--target[Target to collect from]:target:_loadout_targets' \
                '--adopt[Adopt into plugins/]' \
                '--force[Auto-adopt all without prompting]'
            ;;
        status)
            _arguments $global_flags
            ;;
        bundle)
            local -a bundle_commands
            _arguments -C $global_flags \
                '1:subcommand:->bundle_cmds' \
                '*::arg:->bundle_args'
            case $state in
            bundle_cmds)
                bundle_commands=(
                    'create:Create a new bundle'
                    'delete:Delete a bundle'
                    'list:List bundles'
                    'show:Show bundle details'
                    'add:Add skills to a bundle'
                    'drop:Remove skills from a bundle'
                    'activate:Batch install a bundle'
                    'deactivate:Batch uninstall a bundle'
                )
                _describe 'bundle command' bundle_commands
                ;;
            bundle_args)
                case $words[1] in
                create)
                    _arguments '1:name:'
                    ;;
                delete)
                    _arguments \
                        '--force[Force delete active bundle]' \
                        '1:bundle:_loadout_bundles'
                    ;;
                list)
                    _arguments '*:pattern:'
                    ;;
                show)
                    _arguments '1:bundle:_loadout_bundles'
                    ;;
                add)
                    _arguments \
                        '1:bundle:_loadout_bundles' \
                        '*:skill:_loadout_skills'
                    ;;
                drop)
                    _arguments \
                        '1:bundle:_loadout_bundles' \
                        '*:skill:_loadout_skills'
                    ;;
                activate)
                    _arguments \
                        '--all[All targets]' \
                        '--force[Required for activation]' \
                        '1:bundle:_loadout_bundles' \
                        '2::target:_loadout_targets'
                    ;;
                deactivate)
                    _arguments \
                        '--all[All targets]' \
                        '--force[Required for deactivation]' \
                        '1:bundle:_loadout_bundles' \
                        '2::target:_loadout_targets'
                    ;;
                esac
                ;;
            esac
            ;;
        target)
            local -a target_commands
            _arguments -C $global_flags \
                '1:subcommand:->target_cmds' \
                '*::arg:->target_args'
            case $state in
            target_cmds)
                target_commands=(
                    'add:Register a new target'
                    'remove:Unregister a target'
                    'list:Show all targets'
                    'show:Show target details'
                    'detect:Auto-discover agent installations'
                )
                _describe 'target command' target_commands
                ;;
            target_args)
                case $words[1] in
                add)
                    _arguments \
                        '--name[Target name]:name:' \
                        '--scope[Target scope]:scope:(machine repo)' \
                        '--sync[Sync mode]:sync:(auto explicit)' \
                        '1:agent:(claude codex cursor)' \
                        '2::path:_directories'
                    ;;
                remove)
                    _arguments \
                        '--force[Required for removal]' \
                        '1:target:_loadout_targets'
                    ;;
                show)
                    _arguments '1:target:_loadout_targets'
                    ;;
                list)
                    ;;
                detect)
                    _arguments '--force[Auto-add discovered targets]'
                    ;;
                esac
                ;;
            esac
            ;;
        config)
            local -a config_commands
            _arguments -C $global_flags \
                '1:subcommand:->config_cmds'
            case $state in
            config_cmds)
                config_commands=(
                    'show:Display configuration'
                    'edit:Open configuration in editor'
                )
                _describe 'config command' config_commands
                ;;
            esac
            ;;
        completions)
            _arguments \
                '--install[Install completions to shell config]' \
                '1:shell:(bash zsh fish)'
            ;;
        esac
        ;;
    esac
}

_loadout "$@"
"#;

pub const BASH_SCRIPT: &str = r#"# Loadout — agent skill manager
# Generated by: loadout completions bash

_loadout_sources() {
    loadout _complete sources 2>/dev/null
}

_loadout_targets() {
    loadout _complete targets 2>/dev/null
}

_loadout_skills() {
    loadout _complete skills 2>/dev/null
}

_loadout_plugins() {
    loadout _complete plugins 2>/dev/null
}

_loadout_bundles() {
    loadout _complete bundles 2>/dev/null
}

_loadout() {
    local cur prev words cword
    _init_completion || return

    local commands="init add list remove update apply uninstall collect status bundle target config completions"
    local global_flags="--dry-run -n --verbose -v --quiet -q --json --config --help -h --version"

    # Find the primary command (first non-flag arg after 'loadout')
    local cmd="" cmd_idx=0
    for ((i=1; i < cword; i++)); do
        case "${words[i]}" in
            -*) continue ;;
            *)
                if [[ -z "$cmd" ]]; then
                    cmd="${words[i]}"
                    cmd_idx=$i
                fi
                ;;
        esac
    done

    # No command yet — complete command names or global flags
    if [[ -z "$cmd" ]]; then
        if [[ "$cur" == -* ]]; then
            COMPREPLY=($(compgen -W "$global_flags" -- "$cur"))
        else
            COMPREPLY=($(compgen -W "$commands" -- "$cur"))
        fi
        return
    fi

    # Find subcommand for bundle/target/config
    local subcmd=""
    if [[ "$cmd" == "bundle" || "$cmd" == "target" || "$cmd" == "config" ]]; then
        for ((i=cmd_idx+1; i < cword; i++)); do
            case "${words[i]}" in
                -*) continue ;;
                *)
                    if [[ -z "$subcmd" ]]; then
                        subcmd="${words[i]}"
                    fi
                    ;;
            esac
        done
    fi

    case "$cmd" in
    init)
        [[ "$cur" == -* ]] && COMPREPLY=($(compgen -W "$global_flags" -- "$cur"))
        ;;
    add)
        if [[ "$cur" == -* ]]; then
            COMPREPLY=($(compgen -W "$global_flags --source --plugin --skill --ref --symlink --copy" -- "$cur"))
        fi
        ;;
    list)
        if [[ "$cur" == -* ]]; then
            COMPREPLY=($(compgen -W "$global_flags --external" -- "$cur"))
        fi
        ;;
    remove)
        if [[ "$cur" == -* ]]; then
            COMPREPLY=($(compgen -W "$global_flags --force" -- "$cur"))
        else
            COMPREPLY=($(compgen -W "$(_loadout_sources)" -- "$cur"))
        fi
        ;;
    update)
        case "$prev" in
            --ref) ;;
            *)
                if [[ "$cur" == -* ]]; then
                    COMPREPLY=($(compgen -W "$global_flags --ref" -- "$cur"))
                else
                    COMPREPLY=($(compgen -W "$(_loadout_sources)" -- "$cur"))
                fi
                ;;
        esac
        ;;
    apply)
        case "$prev" in
            --skill) COMPREPLY=($(compgen -W "$(_loadout_skills)" -- "$cur")) ;;
            --plugin) COMPREPLY=($(compgen -W "$(_loadout_plugins)" -- "$cur")) ;;
            --bundle) COMPREPLY=($(compgen -W "$(_loadout_bundles)" -- "$cur")) ;;
            --target) COMPREPLY=($(compgen -W "$(_loadout_targets)" -- "$cur")) ;;
            *)
                [[ "$cur" == -* ]] && COMPREPLY=($(compgen -W "$global_flags --all --skill --plugin --bundle --target --force -f --interactive -i" -- "$cur"))
                ;;
        esac
        ;;
    uninstall)
        case "$prev" in
            --skill) COMPREPLY=($(compgen -W "$(_loadout_skills)" -- "$cur")) ;;
            --plugin) COMPREPLY=($(compgen -W "$(_loadout_plugins)" -- "$cur")) ;;
            --bundle) COMPREPLY=($(compgen -W "$(_loadout_bundles)" -- "$cur")) ;;
            --target) COMPREPLY=($(compgen -W "$(_loadout_targets)" -- "$cur")) ;;
            *)
                [[ "$cur" == -* ]] && COMPREPLY=($(compgen -W "$global_flags --skill --plugin --bundle --target --force" -- "$cur"))
                ;;
        esac
        ;;
    collect)
        case "$prev" in
            --skill) COMPREPLY=($(compgen -W "$(_loadout_skills)" -- "$cur")) ;;
            --target) COMPREPLY=($(compgen -W "$(_loadout_targets)" -- "$cur")) ;;
            *)
                [[ "$cur" == -* ]] && COMPREPLY=($(compgen -W "$global_flags --skill --target --adopt --force" -- "$cur"))
                ;;
        esac
        ;;
    status)
        [[ "$cur" == -* ]] && COMPREPLY=($(compgen -W "$global_flags" -- "$cur"))
        ;;
    bundle)
        if [[ -z "$subcmd" ]]; then
            if [[ "$cur" == -* ]]; then
                COMPREPLY=($(compgen -W "$global_flags" -- "$cur"))
            else
                COMPREPLY=($(compgen -W "create delete list show add drop activate deactivate" -- "$cur"))
            fi
        else
            case "$subcmd" in
            create)
                ;;
            delete)
                if [[ "$cur" == -* ]]; then
                    COMPREPLY=($(compgen -W "--force" -- "$cur"))
                else
                    COMPREPLY=($(compgen -W "$(_loadout_bundles)" -- "$cur"))
                fi
                ;;
            show)
                [[ "$cur" != -* ]] && COMPREPLY=($(compgen -W "$(_loadout_bundles)" -- "$cur"))
                ;;
            list)
                ;;
            add|drop)
                # First arg after subcmd is bundle name, rest are skills
                local args_after=0
                for ((i=cmd_idx+1; i < cword; i++)); do
                    case "${words[i]}" in
                        "$subcmd"|--*) continue ;;
                        *) ((args_after++)) ;;
                    esac
                done
                if [[ $args_after -eq 0 ]]; then
                    COMPREPLY=($(compgen -W "$(_loadout_bundles)" -- "$cur"))
                else
                    COMPREPLY=($(compgen -W "$(_loadout_skills)" -- "$cur"))
                fi
                ;;
            activate|deactivate)
                case "$prev" in
                    --target) COMPREPLY=($(compgen -W "$(_loadout_targets)" -- "$cur")) ;;
                    *)
                        if [[ "$cur" == -* ]]; then
                            COMPREPLY=($(compgen -W "--all --force --target" -- "$cur"))
                        else
                            COMPREPLY=($(compgen -W "$(_loadout_bundles)" -- "$cur"))
                        fi
                        ;;
                esac
                ;;
            esac
        fi
        ;;
    target)
        if [[ -z "$subcmd" ]]; then
            if [[ "$cur" == -* ]]; then
                COMPREPLY=($(compgen -W "$global_flags" -- "$cur"))
            else
                COMPREPLY=($(compgen -W "add remove list show detect" -- "$cur"))
            fi
        else
            case "$subcmd" in
            add)
                case "$prev" in
                    --name) ;;
                    --scope) COMPREPLY=($(compgen -W "machine repo" -- "$cur")) ;;
                    --sync) COMPREPLY=($(compgen -W "auto explicit" -- "$cur")) ;;
                    *)
                        if [[ "$cur" == -* ]]; then
                            COMPREPLY=($(compgen -W "--name --scope --sync" -- "$cur"))
                        else
                            COMPREPLY=($(compgen -W "claude codex cursor" -- "$cur"))
                        fi
                        ;;
                esac
                ;;
            remove)
                if [[ "$cur" == -* ]]; then
                    COMPREPLY=($(compgen -W "--force" -- "$cur"))
                else
                    COMPREPLY=($(compgen -W "$(_loadout_targets)" -- "$cur"))
                fi
                ;;
            show)
                COMPREPLY=($(compgen -W "$(_loadout_targets)" -- "$cur"))
                ;;
            detect)
                [[ "$cur" == -* ]] && COMPREPLY=($(compgen -W "--force" -- "$cur"))
                ;;
            esac
        fi
        ;;
    config)
        if [[ -z "$subcmd" ]]; then
            COMPREPLY=($(compgen -W "show edit" -- "$cur"))
        fi
        ;;
    completions)
        if [[ "$cur" == -* ]]; then
            COMPREPLY=($(compgen -W "--install" -- "$cur"))
        else
            COMPREPLY=($(compgen -W "bash zsh fish" -- "$cur"))
        fi
        ;;
    esac
}

complete -o default -F _loadout loadout
"#;

pub const FISH_SCRIPT: &str = r#"# Loadout — agent skill manager
# Generated by: loadout completions fish

# Helpers for dynamic completions
function __loadout_sources
    loadout _complete sources 2>/dev/null
end

function __loadout_targets
    loadout _complete targets 2>/dev/null
end

function __loadout_skills
    loadout _complete skills 2>/dev/null
end

function __loadout_plugins
    loadout _complete plugins 2>/dev/null
end

function __loadout_bundles
    loadout _complete bundles 2>/dev/null
end

function __loadout_needs_command
    set -l cmd (commandline -opc)
    test (count $cmd) -eq 1
end

function __loadout_using_command
    set -l cmd (commandline -opc)
    test (count $cmd) -gt 1; and test "$cmd[2]" = "$argv[1]"
end

function __loadout_using_subcommand
    set -l cmd (commandline -opc)
    test (count $cmd) -gt 2; and test "$cmd[2]" = "$argv[1]"; and test "$cmd[3]" = "$argv[2]"
end

# Global flags
complete -c loadout -l dry-run -s n -d 'Preview changes without writing'
complete -c loadout -l verbose -s v -d 'Show detailed output'
complete -c loadout -l quiet -s q -d 'Suppress output'
complete -c loadout -l json -d 'Output as JSON'
complete -c loadout -l config -r -d 'Override config file path'
complete -c loadout -l help -s h -d 'Show help'
complete -c loadout -l version -d 'Show version'

# Top-level commands
complete -c loadout -f -n __loadout_needs_command -a init -d 'Initialize loadout configuration'
complete -c loadout -f -n __loadout_needs_command -a add -d 'Add a skill source'
complete -c loadout -f -n __loadout_needs_command -a list -d 'List skills or sources'
complete -c loadout -f -n __loadout_needs_command -a remove -d 'Remove a skill source'
complete -c loadout -f -n __loadout_needs_command -a update -d 'Update sources from remote'
complete -c loadout -f -n __loadout_needs_command -a apply -d 'Apply skills to targets'
complete -c loadout -f -n __loadout_needs_command -a uninstall -d 'Uninstall skills from targets'
complete -c loadout -f -n __loadout_needs_command -a collect -d 'Collect edited skills back'
complete -c loadout -f -n __loadout_needs_command -a status -d 'Show current install state'
complete -c loadout -f -n __loadout_needs_command -a bundle -d 'Manage skill bundles'
complete -c loadout -f -n __loadout_needs_command -a target -d 'Manage install targets'
complete -c loadout -f -n __loadout_needs_command -a config -d 'View or edit configuration'
complete -c loadout -f -n __loadout_needs_command -a completions -d 'Generate shell completions'

# add
complete -c loadout -f -n '__loadout_using_command add' -l source -r -d 'Override source name'
complete -c loadout -f -n '__loadout_using_command add' -l plugin -r -d 'Override plugin name'
complete -c loadout -f -n '__loadout_using_command add' -l skill -r -d 'Override skill name'
complete -c loadout -f -n '__loadout_using_command add' -l ref -r -d 'Pin to git ref'
complete -c loadout -f -n '__loadout_using_command add' -l symlink -d 'Symlink local source'
complete -c loadout -f -n '__loadout_using_command add' -l copy -d 'Copy local source'

# list
complete -c loadout -f -n '__loadout_using_command list' -l external -d 'List sources instead'

# remove
complete -c loadout -f -n '__loadout_using_command remove' -l force -d 'Force removal'
complete -c loadout -f -n '__loadout_using_command remove' -a '(__loadout_sources)'

# update
complete -c loadout -f -n '__loadout_using_command update' -l ref -r -d 'Switch to ref'
complete -c loadout -f -n '__loadout_using_command update' -a '(__loadout_sources)'

# apply
complete -c loadout -f -n '__loadout_using_command apply' -l all -d 'Apply all skills'
complete -c loadout -f -n '__loadout_using_command apply' -l skill -r -a '(__loadout_skills)' -d 'Specific skill'
complete -c loadout -f -n '__loadout_using_command apply' -l plugin -r -a '(__loadout_plugins)' -d 'All skills in plugin'
complete -c loadout -f -n '__loadout_using_command apply' -l bundle -r -a '(__loadout_bundles)' -d 'Specific bundle'
complete -c loadout -f -n '__loadout_using_command apply' -l target -r -a '(__loadout_targets)' -d 'Target'
complete -c loadout -f -n '__loadout_using_command apply' -l force -s f -d 'Overwrite without prompting'
complete -c loadout -f -n '__loadout_using_command apply' -l interactive -s i -d 'Interactive conflict resolution'

# uninstall
complete -c loadout -f -n '__loadout_using_command uninstall' -l skill -r -a '(__loadout_skills)' -d 'Specific skill'
complete -c loadout -f -n '__loadout_using_command uninstall' -l plugin -r -a '(__loadout_plugins)' -d 'All skills in plugin'
complete -c loadout -f -n '__loadout_using_command uninstall' -l bundle -r -a '(__loadout_bundles)' -d 'Specific bundle'
complete -c loadout -f -n '__loadout_using_command uninstall' -l target -r -a '(__loadout_targets)' -d 'Target'
complete -c loadout -f -n '__loadout_using_command uninstall' -l force -d 'Actually perform uninstall'

# collect
complete -c loadout -f -n '__loadout_using_command collect' -l skill -r -a '(__loadout_skills)' -d 'Specific skill'
complete -c loadout -f -n '__loadout_using_command collect' -l target -r -a '(__loadout_targets)' -d 'Target'
complete -c loadout -f -n '__loadout_using_command collect' -l adopt -d 'Adopt into plugins/'
complete -c loadout -f -n '__loadout_using_command collect' -l force -d 'Auto-adopt all'

# bundle subcommands
complete -c loadout -f -n '__loadout_using_command bundle' -a create -d 'Create a new bundle'
complete -c loadout -f -n '__loadout_using_command bundle' -a delete -d 'Delete a bundle'
complete -c loadout -f -n '__loadout_using_command bundle' -a list -d 'List bundles'
complete -c loadout -f -n '__loadout_using_command bundle' -a show -d 'Show bundle details'
complete -c loadout -f -n '__loadout_using_command bundle' -a add -d 'Add skills to a bundle'
complete -c loadout -f -n '__loadout_using_command bundle' -a drop -d 'Remove skills from a bundle'
complete -c loadout -f -n '__loadout_using_command bundle' -a activate -d 'Batch install a bundle'
complete -c loadout -f -n '__loadout_using_command bundle' -a deactivate -d 'Batch uninstall a bundle'

complete -c loadout -f -n '__loadout_using_subcommand bundle delete' -l force -d 'Force delete'
complete -c loadout -f -n '__loadout_using_subcommand bundle delete' -a '(__loadout_bundles)'
complete -c loadout -f -n '__loadout_using_subcommand bundle show' -a '(__loadout_bundles)'
complete -c loadout -f -n '__loadout_using_subcommand bundle add' -a '(__loadout_bundles) (__loadout_skills)'
complete -c loadout -f -n '__loadout_using_subcommand bundle drop' -a '(__loadout_bundles) (__loadout_skills)'
complete -c loadout -f -n '__loadout_using_subcommand bundle activate' -l all -d 'All targets'
complete -c loadout -f -n '__loadout_using_subcommand bundle activate' -l force -d 'Required'
complete -c loadout -f -n '__loadout_using_subcommand bundle activate' -a '(__loadout_bundles)'
complete -c loadout -f -n '__loadout_using_subcommand bundle deactivate' -l all -d 'All targets'
complete -c loadout -f -n '__loadout_using_subcommand bundle deactivate' -l force -d 'Required'
complete -c loadout -f -n '__loadout_using_subcommand bundle deactivate' -a '(__loadout_bundles)'

# target subcommands
complete -c loadout -f -n '__loadout_using_command target' -a add -d 'Register a new target'
complete -c loadout -f -n '__loadout_using_command target' -a remove -d 'Unregister a target'
complete -c loadout -f -n '__loadout_using_command target' -a list -d 'Show all targets'
complete -c loadout -f -n '__loadout_using_command target' -a show -d 'Show target details'
complete -c loadout -f -n '__loadout_using_command target' -a detect -d 'Auto-discover agents'

complete -c loadout -f -n '__loadout_using_subcommand target add' -l name -r -d 'Target name'
complete -c loadout -f -n '__loadout_using_subcommand target add' -l scope -r -a 'machine repo' -d 'Scope'
complete -c loadout -f -n '__loadout_using_subcommand target add' -l sync -r -a 'auto explicit' -d 'Sync mode'
complete -c loadout -f -n '__loadout_using_subcommand target add' -a 'claude codex cursor'
complete -c loadout -f -n '__loadout_using_subcommand target remove' -l force -d 'Required for removal'
complete -c loadout -f -n '__loadout_using_subcommand target remove' -a '(__loadout_targets)'
complete -c loadout -f -n '__loadout_using_subcommand target show' -a '(__loadout_targets)'
complete -c loadout -f -n '__loadout_using_subcommand target detect' -l force -d 'Auto-add'

# config subcommands
complete -c loadout -f -n '__loadout_using_command config' -a show -d 'Display configuration'
complete -c loadout -f -n '__loadout_using_command config' -a edit -d 'Open in editor'

# completions
complete -c loadout -f -n '__loadout_using_command completions' -l install -d 'Install to shell config'
complete -c loadout -f -n '__loadout_using_command completions' -a 'bash zsh fish'
"#;

/// Install completions for zsh.
pub fn install_zsh(quiet: bool) -> Result<PathBuf> {
    let home = dirs::home_dir().context("cannot determine home directory")?;

    // Prefer oh-my-zsh completions dir if it exists
    let omz_dir = home.join(".oh-my-zsh/completions");
    let (dest, extra) = if omz_dir.is_dir() {
        (omz_dir.join("_loadout"), None)
    } else {
        let zfunc = home.join(".zfunc");
        fs::create_dir_all(&zfunc)
            .with_context(|| format!("failed to create {}", zfunc.display()))?;

        let needs_fpath = {
            let zshrc = home.join(".zshrc");
            if let Ok(content) = fs::read_to_string(&zshrc) {
                !content.contains(".zfunc")
            } else {
                true
            }
        };

        let hint = if needs_fpath {
            Some(format!(
                "\n{}  Add to {} (before compinit):\n\n    {}\n    {}",
                "Note:".yellow().bold(),
                "~/.zshrc".bold(),
                "fpath=(~/.zfunc $fpath)",
                "autoload -Uz compinit && compinit",
            ))
        } else {
            None
        };

        (zfunc.join("_loadout"), hint)
    };

    fs::write(&dest, ZSH_SCRIPT)
        .with_context(|| format!("failed to write {}", dest.display()))?;

    if !quiet {
        println!(
            "{} Installed zsh completions to {}",
            "✓".green(),
            dest.display().to_string().bold()
        );
        if let Some(hint) = extra {
            println!("{}", hint);
        }
        println!("\nRestart your shell or run: {}", "exec zsh".bold());
    }

    Ok(dest)
}

/// Install completions for bash.
pub fn install_bash(quiet: bool) -> Result<PathBuf> {
    let home = dirs::home_dir().context("cannot determine home directory")?;
    let comp_dir = home.join(".local/share/bash-completion/completions");
    fs::create_dir_all(&comp_dir)
        .with_context(|| format!("failed to create {}", comp_dir.display()))?;

    let dest = comp_dir.join("loadout");
    fs::write(&dest, BASH_SCRIPT)
        .with_context(|| format!("failed to write {}", dest.display()))?;

    if !quiet {
        println!(
            "{} Installed bash completions to {}",
            "✓".green(),
            dest.display().to_string().bold()
        );
        println!(
            "\nRestart your shell or run: {}",
            format!("source {}", dest.display()).bold()
        );
    }

    Ok(dest)
}

/// Install completions for fish.
pub fn install_fish(quiet: bool) -> Result<PathBuf> {
    let home = dirs::home_dir().context("cannot determine home directory")?;
    let comp_dir = home.join(".config/fish/completions");
    fs::create_dir_all(&comp_dir)
        .with_context(|| format!("failed to create {}", comp_dir.display()))?;

    let dest = comp_dir.join("loadout.fish");
    fs::write(&dest, FISH_SCRIPT)
        .with_context(|| format!("failed to write {}", dest.display()))?;

    if !quiet {
        println!(
            "{} Installed fish completions to {}",
            "✓".green(),
            dest.display().to_string().bold()
        );
        println!("\nCompletions are available in new fish sessions.");
    }

    Ok(dest)
}
