use anyhow::{Context, Result};
use colored::Colorize;
use std::fs;
use std::path::PathBuf;

/// Help text shown in `equip completions --help`.
pub const AFTER_HELP: &str = r#"SETUP:

  zsh (recommended — add to fpath):
    mkdir -p ~/.zfunc
    equip completions zsh > ~/.zfunc/_equip

    # Add to ~/.zshrc BEFORE compinit:
    fpath=(~/.zfunc $fpath)
    autoload -Uz compinit && compinit

  zsh (oh-my-zsh):
    mkdir -p ~/.oh-my-zsh/completions
    equip completions zsh > ~/.oh-my-zsh/completions/_equip

  zsh (inline eval — slower, runs on every shell start):
    # Add to ~/.zshrc:
    eval "$(equip completions zsh)"

  bash (bash-completion — recommended):
    mkdir -p ~/.local/share/bash-completion/completions
    equip completions bash > ~/.local/share/bash-completion/completions/equip

  bash (inline eval):
    # Add to ~/.bashrc:
    eval "$(equip completions bash)"

  fish:
    equip completions fish > ~/.config/fish/completions/equip.fish

  Auto-install (writes to the standard location for your shell):
    equip completions zsh --install
    equip completions bash --install
    equip completions fish --install"#;

pub const ZSH_SCRIPT: &str = r#"#compdef equip

# Equip — agent skill manager
# Generated by: equip completions zsh

_equip() {
    _equip_sources() {
        local -a sources
        sources=(${(f)"$(equip _complete sources 2>/dev/null)"})
        [[ ${#sources} -gt 0 ]] && _describe 'source' sources
    }

    _equip_agents() {
        local -a agents
        agents=(${(f)"$(equip _complete agents 2>/dev/null)"})
        [[ ${#agents} -gt 0 ]] && _describe 'agent' agents
    }

    _equip_skills() {
        local -a skills
        skills=(${(f)"$(equip _complete skills 2>/dev/null)"})
        [[ ${#skills} -gt 0 ]] && compadd -a skills
    }

    _equip_plugins() {
        local -a plugins
        plugins=(${(f)"$(equip _complete plugins 2>/dev/null)"})
        [[ ${#plugins} -gt 0 ]] && compadd -a plugins
    }

    _equip_kits() {
        local -a kits
        kits=(${(f)"$(equip _complete kits 2>/dev/null)"})
        [[ ${#kits} -gt 0 ]] && _describe 'kit' kits
    }
    local -a global_flags
    global_flags=(
        '(-n --dry-run)'{-n,--dry-run}'[Preview changes without writing]'
        '(-v --verbose)'{-v,--verbose}'[Show detailed output]'
        '(-q --quiet)'{-q,--quiet}'[Suppress output]'
        '--json[Output as JSON]'
        '--config[Override config file path]:config file:_files'
        '(-h --help)'{-h,--help}'[Show help]'
        '--version[Show version]'
    )

    _arguments -C \
        $global_flags \
        '1:command:->commands' \
        '*::arg:->args'

    case $state in
    commands)
        local -a commands
        commands=(
            'init:Initialize equip configuration'
            'add:Add a skill source'
            'list:List skills'
            'remove:Remove local skills or a source'
            'collect:Collect skills from an agent back to the library'
            'status:Show current install state'
            'source:Manage sources'
            'kit:Manage skill kits'
            'agent:Manage agents'
            'config:View or edit configuration'
            'completions:Generate shell completions'
        )
        _describe 'command' commands
        ;;
    args)
        case $words[1] in
        init)
            _arguments $global_flags \
                '1::url:'
            ;;
        add)
            _arguments $global_flags \
                '--source[Override source name]:name:' \
                '--plugin[Override plugin name]:name:' \
                '--skill[Override skill name]:name:' \
                '--ref[Pin to git ref]:ref:' \
                '(--copy)--symlink[Symlink local source]' \
                '(--symlink)--copy[Copy local source]' \
                '1:url:_files'
            ;;
        list)
            _arguments $global_flags \
                '--external[List sources instead of skills]' \
                '*:pattern:'
            ;;
        remove)
            _arguments $global_flags \
                '--force[Force removal even if installed]' \
                '*:pattern:_equip_skills'
            ;;
        collect)
            _arguments $global_flags \
                '--agent[Agent to collect from]:agent:_equip_agents' \
                '--adopt[Adopt into the local source]' \
                '(-f --force)'{-f,--force}'[Auto-adopt all without prompting]' \
                '(-i --interactive)'{-i,--interactive}'[Interactive skill selection]' \
                '*:pattern:_equip_skills'
            ;;
        status)
            _arguments $global_flags
            ;;
        source)
            local -a source_commands
            _arguments -C $global_flags \
                '1:subcommand:->source_cmds' \
                '*::arg:->source_args'
            case $state in
            source_cmds)
                source_commands=(
                    'add:Add a skill source'
                    'list:List configured sources'
                    'remove:Remove a source'
                    'update:Update sources from remote'
                )
                _describe 'source command' source_commands
                ;;
            source_args)
                case $words[1] in
                add)
                    _arguments \
                        '--source[Override source name]:name:' \
                        '--plugin[Override plugin name]:name:' \
                        '--skill[Override skill name]:name:' \
                        '--ref[Pin to git ref]:ref:' \
                        '(--copy)--symlink[Symlink local source]' \
                        '(--symlink)--copy[Copy local source]' \
                        '1:url:_files'
                    ;;
                list)
                    ;;
                remove)
                    _arguments \
                        '--force[Force removal even if installed]' \
                        '1::source:_equip_sources'
                    ;;
                update)
                    _arguments \
                        '--ref[Switch to ref or "latest" to unpin]:ref:' \
                        '1::source:_equip_sources'
                    ;;
                esac
                ;;
            esac
            ;;
        kit)
            local -a kit_commands
            _arguments -C $global_flags \
                '1:subcommand:->kit_cmds' \
                '*::arg:->kit_args'
            case $state in
            kit_cmds)
                kit_commands=(
                    'create:Create a new kit'
                    'delete:Delete a kit'
                    'list:List kits'
                    'show:Show kit details'
                    'add:Add skills to a kit'
                    'drop:Remove skills from a kit'
                )
                _describe 'kit command' kit_commands
                ;;
            kit_args)
                case $words[1] in
                create)
                    _arguments '1:name:'
                    ;;
                delete)
                    _arguments \
                        '--force[Force delete active kit]' \
                        '1:kit:_equip_kits'
                    ;;
                list)
                    _arguments '*:pattern:'
                    ;;
                show)
                    _arguments '1:kit:_equip_kits'
                    ;;
                add)
                    _arguments \
                        '1:kit:_equip_kits' \
                        '*:skill:_equip_skills'
                    ;;
                drop)
                    _arguments \
                        '1:kit:_equip_kits' \
                        '*:skill:_equip_skills'
                    ;;
                esac
                ;;
            esac
            ;;
        agent)
            local -a agent_commands
            _arguments -C $global_flags \
                '1:subcommand:->agent_cmds' \
                '*::arg:->agent_args'
            case $state in
            agent_cmds)
                agent_commands=(
                    'add:Register a new agent'
                    'remove:Unregister an agent'
                    'list:Show all agents'
                    'show:Show agent details'
                    'detect:Auto-discover agent installations'
                    'equip:Equip skills to agents'
                    'unequip:Unequip skills from agents'
                    'collect:Collect edited skills back from agent'
                )
                _describe 'agent command' agent_commands
                ;;
            agent_args)
                case $words[1] in
                add)
                    _arguments \
                        '--name[Agent name]:name:' \
                        '--scope[Agent scope]:scope:(machine repo)' \
                        '--sync[Sync mode]:sync:(auto explicit)' \
                        '1:agent:(claude codex cursor)' \
                        '2::path:_directories'
                    ;;
                remove)
                    _arguments \
                        '--force[Required for removal]' \
                        '1:agent:_equip_agents'
                    ;;
                show)
                    _arguments '1:agent:_equip_agents'
                    ;;
                list)
                    ;;
                detect)
                    _arguments '--force[Auto-add discovered agents]'
                    ;;
                equip)
                    _arguments \
                        '*'{-a,--agent}'[Agent to equip]:agent:_equip_agents' \
                        '--all[All configured skills]' \
                        '(-k --kit)'{-k,--kit}'[Kit to equip]:kit:_equip_kits' \
                        '(-s --save-kit)'{-s,--save-kit}'[Save selection as kit]:name:' \
                        '(-f --force)'{-f,--force}'[Overwrite without prompting]' \
                        '(-i --interactive)'{-i,--interactive}'[Interactive conflict resolution]' \
                        '*:pattern:_equip_skills'
                    ;;
                unequip)
                    _arguments \
                        '*'{-a,--agent}'[Agent to unequip]:agent:_equip_agents' \
                        '--all[All equipped skills]' \
                        '(-k --kit)'{-k,--kit}'[Kit to unequip]:kit:_equip_kits' \
                        '(-f --force)'{-f,--force}'[Force unequip]' \
                        '*:pattern:_equip_skills'
                    ;;
                collect)
                    _arguments \
                        '--agent[Agent to collect from]:agent:_equip_agents' \
                        '--adopt[Adopt into the local source]' \
                        '(-f --force)'{-f,--force}'[Auto-adopt all without prompting]' \
                        '(-i --interactive)'{-i,--interactive}'[Interactive skill selection]' \
                        '*:pattern:_equip_skills'
                    ;;
                esac
                ;;
            esac
            ;;
        config)
            local -a config_commands
            _arguments -C $global_flags \
                '1:subcommand:->config_cmds'
            case $state in
            config_cmds)
                config_commands=(
                    'show:Display configuration'
                    'edit:Open configuration in editor'
                )
                _describe 'config command' config_commands
                ;;
            esac
            ;;
        completions)
            _arguments \
                '--install[Install completions to shell config]' \
                '1:shell:(bash zsh fish)'
            ;;
        esac
        ;;
    esac
}

_equip "$@"
"#;

pub const BASH_SCRIPT: &str = r#"# Equip — agent skill manager
# Generated by: equip completions bash

_equip_sources() {
    equip _complete sources 2>/dev/null
}

_equip_agents() {
    equip _complete agents 2>/dev/null
}

_equip_skills() {
    equip _complete skills 2>/dev/null
}

_equip_plugins() {
    equip _complete plugins 2>/dev/null
}

_equip_kits() {
    equip _complete kits 2>/dev/null
}

# Progressive skill identity completion: source:plugin/skill
# Level 1: "m<TAB>"  → "my-source:"
# Level 2: "my-source:ex<TAB>"  → "my-source:example-plugin/"
# Level 3: "my-source:example-plugin/si<TAB>"  → "my-source:example-plugin/single-skill"
# Skips completion if cur contains glob characters (* ? [)
_equip_complete_identity() {
    local cur="$1"

    # Don't complete if the word already contains glob characters
    [[ "$cur" == *[\*\?\[]* ]] && return

    local IFS=$'\n'
    local all_skills
    all_skills=($(_equip_skills))
    [[ ${#all_skills[@]} -eq 0 ]] && return

    if [[ "$cur" != *:* ]]; then
        # No colon — complete source names, append ":"
        local -A seen
        local sources=()
        for s in "${all_skills[@]}"; do
            local src="${s%%:*}"
            if [[ -z "${seen[$src]+x}" ]]; then
                seen[$src]=1
                sources+=("$src")
            fi
        done
        COMPREPLY=($(compgen -W "${sources[*]}" -- "$cur"))
        if [[ ${#COMPREPLY[@]} -eq 1 ]]; then
            COMPREPLY=("${COMPREPLY[0]}:")
        fi
        compopt -o nospace
    elif [[ "$cur" != */* ]]; then
        # Has colon, no slash — complete plugin names, append "/"
        local source="${cur%%:*}"
        local partial="${cur#*:}"
        local -A seen
        local plugins=()
        for s in "${all_skills[@]}"; do
            if [[ "$s" == "${source}:"* ]]; then
                local rest="${s#*:}"
                local plug="${rest%%/*}"
                if [[ -z "${seen[$plug]+x}" ]]; then
                    seen[$plug]=1
                    plugins+=("$plug")
                fi
            fi
        done
        COMPREPLY=($(compgen -P "${source}:" -W "${plugins[*]}" -- "$partial"))
        if [[ ${#COMPREPLY[@]} -eq 1 ]]; then
            COMPREPLY=("${COMPREPLY[0]}/")
        fi
        compopt -o nospace
    else
        # Has colon and slash — complete skill name
        local source="${cur%%:*}"
        local rest="${cur#*:}"
        local plugin="${rest%%/*}"
        local partial="${rest#*/}"
        local skills=()
        for s in "${all_skills[@]}"; do
            if [[ "$s" == "${source}:${plugin}/"* ]]; then
                skills+=("${s#${source}:${plugin}/}")
            fi
        done
        COMPREPLY=($(compgen -P "${source}:${plugin}/" -W "${skills[*]}" -- "$partial"))
    fi

    # Fix readline display when completions contain colons
    [[ ${#COMPREPLY[@]} -gt 0 ]] && __ltrim_colon_completions "$cur"
}

_equip() {
    local cur prev words cword
    _init_completion -n : || return

    local commands="init add list remove collect update status kit agent config completions"
    local global_flags="--dry-run -n --verbose -v --quiet -q --json --config --help -h --version"
    local equip_flags="--force -f --interactive -i --save -s --remove -r --all"

    # Find the primary command (skip flags and @agent/+kit tokens)
    local cmd="" cmd_idx=0
    local in_shorthand=false
    for ((i=1; i < cword; i++)); do
        case "${words[i]}" in
            -*) continue ;;
            @*|+*) in_shorthand=true; continue ;;
            *)
                if [[ -z "$cmd" ]]; then
                    cmd="${words[i]}"
                    cmd_idx=$i
                fi
                ;;
        esac
    done
    [[ "$cur" == @* || "$cur" == +* ]] && in_shorthand=true

    # No recognized command — either shorthand mode or top-level completion
    if [[ -z "$cmd" ]]; then
        if [[ "$cur" == @* ]]; then
            local partial="${cur#@}"
            COMPREPLY=($(compgen -P "@" -W "$(_equip_agents)" -- "$partial"))
            return
        elif [[ "$cur" == +* ]]; then
            local partial="${cur#+}"
            COMPREPLY=($(compgen -P "+" -W "$(_equip_kits)" -- "$partial"))
            return
        elif $in_shorthand; then
            # After @agent/+kit tokens, complete flags or skill identities
            if [[ "$cur" == -* ]]; then
                COMPREPLY=($(compgen -W "$global_flags $equip_flags" -- "$cur"))
            else
                _equip_complete_identity "$cur"
            fi
            return
        fi

        if [[ "$cur" == -* ]]; then
            COMPREPLY=($(compgen -W "$global_flags" -- "$cur"))
        else
            COMPREPLY=($(compgen -W "$commands" -- "$cur"))
        fi
        return
    fi

    # Find subcommand for kit/agent/config
    local subcmd=""
    if [[ "$cmd" == "source" || "$cmd" == "kit" || "$cmd" == "agent" || "$cmd" == "config" ]]; then
        for ((i=cmd_idx+1; i < cword; i++)); do
            case "${words[i]}" in
                -*) continue ;;
                *)
                    if [[ -z "$subcmd" ]]; then
                        subcmd="${words[i]}"
                    fi
                    ;;
            esac
        done
    fi

    case "$cmd" in
    init)
        [[ "$cur" == -* ]] && COMPREPLY=($(compgen -W "$global_flags" -- "$cur"))
        ;;
    add)
        if [[ "$cur" == -* ]]; then
            COMPREPLY=($(compgen -W "$global_flags --source --plugin --skill --ref --symlink --copy" -- "$cur"))
        else
            _filedir
        fi
        ;;
    list)
        if [[ "$cur" == -* ]]; then
            COMPREPLY=($(compgen -W "$global_flags --external --fzf" -- "$cur"))
        else
            _equip_complete_identity "$cur"
        fi
        ;;
    remove)
        if [[ "$cur" == -* ]]; then
            COMPREPLY=($(compgen -W "$global_flags --force" -- "$cur"))
        else
            _equip_complete_identity "$cur"
        fi
        ;;
    collect)
        case "$prev" in
            --agent) COMPREPLY=($(compgen -W "$(_equip_agents)" -- "$cur")) ;;
            *)
                if [[ "$cur" == -* ]]; then
                    COMPREPLY=($(compgen -W "$global_flags --agent --adopt --force -f --interactive -i" -- "$cur"))
                else
                    _equip_complete_identity "$cur"
                fi
                ;;
        esac
        ;;
    status)
        [[ "$cur" == -* ]] && COMPREPLY=($(compgen -W "$global_flags" -- "$cur"))
        ;;
    source)
        if [[ -z "$subcmd" ]]; then
            if [[ "$cur" == -* ]]; then
                COMPREPLY=($(compgen -W "$global_flags" -- "$cur"))
            else
                COMPREPLY=($(compgen -W "add list remove update" -- "$cur"))
            fi
        else
            case "$subcmd" in
            add)
                if [[ "$cur" == -* ]]; then
                    COMPREPLY=($(compgen -W "--source --plugin --skill --ref --symlink --copy" -- "$cur"))
                else
                    _filedir
                fi
                ;;
            list)
                ;;
            remove)
                if [[ "$cur" == -* ]]; then
                    COMPREPLY=($(compgen -W "--force" -- "$cur"))
                else
                    COMPREPLY=($(compgen -W "$(_equip_sources)" -- "$cur"))
                fi
                ;;
            update)
                case "$prev" in
                    --ref) ;;
                    *)
                        if [[ "$cur" == -* ]]; then
                            COMPREPLY=($(compgen -W "--ref" -- "$cur"))
                        else
                            COMPREPLY=($(compgen -W "$(_equip_sources)" -- "$cur"))
                        fi
                        ;;
                esac
                ;;
            esac
        fi
        ;;
    kit)
        if [[ -z "$subcmd" ]]; then
            if [[ "$cur" == -* ]]; then
                COMPREPLY=($(compgen -W "$global_flags" -- "$cur"))
            else
                COMPREPLY=($(compgen -W "create delete list show add drop" -- "$cur"))
            fi
        else
            case "$subcmd" in
            create)
                ;;
            delete)
                if [[ "$cur" == -* ]]; then
                    COMPREPLY=($(compgen -W "--force" -- "$cur"))
                else
                    COMPREPLY=($(compgen -W "$(_equip_kits)" -- "$cur"))
                fi
                ;;
            show)
                [[ "$cur" != -* ]] && COMPREPLY=($(compgen -W "$(_equip_kits)" -- "$cur"))
                ;;
            list)
                ;;
            add|drop)
                local args_after=0
                for ((i=cmd_idx+1; i < cword; i++)); do
                    case "${words[i]}" in
                        "$subcmd"|--*) continue ;;
                        *) ((args_after++)) ;;
                    esac
                done
                if [[ $args_after -eq 0 ]]; then
                    COMPREPLY=($(compgen -W "$(_equip_kits)" -- "$cur"))
                else
                    _equip_complete_identity "$cur"
                fi
                ;;
            esac
        fi
        ;;
    agent)
        if [[ -z "$subcmd" ]]; then
            if [[ "$cur" == -* ]]; then
                COMPREPLY=($(compgen -W "$global_flags" -- "$cur"))
            else
                COMPREPLY=($(compgen -W "add remove list show detect collect" -- "$cur"))
            fi
        else
            case "$subcmd" in
            add)
                case "$prev" in
                    --name) ;;
                    --scope) COMPREPLY=($(compgen -W "machine repo" -- "$cur")) ;;
                    --sync) COMPREPLY=($(compgen -W "auto explicit" -- "$cur")) ;;
                    *)
                        if [[ "$cur" == -* ]]; then
                            COMPREPLY=($(compgen -W "--name --scope --sync" -- "$cur"))
                        else
                            COMPREPLY=($(compgen -W "claude codex cursor gemini vscode" -- "$cur"))
                        fi
                        ;;
                esac
                ;;
            remove)
                if [[ "$cur" == -* ]]; then
                    COMPREPLY=($(compgen -W "--force" -- "$cur"))
                else
                    COMPREPLY=($(compgen -W "$(_equip_agents)" -- "$cur"))
                fi
                ;;
            show)
                COMPREPLY=($(compgen -W "$(_equip_agents)" -- "$cur"))
                ;;
            detect)
                [[ "$cur" == -* ]] && COMPREPLY=($(compgen -W "--force" -- "$cur"))
                ;;
            collect)
                case "$prev" in
                    --agent) COMPREPLY=($(compgen -W "$(_equip_agents)" -- "$cur")) ;;
                    *)
                        if [[ "$cur" == -* ]]; then
                            COMPREPLY=($(compgen -W "--agent --adopt --force -f --interactive -i" -- "$cur"))
                        else
                            _equip_complete_identity "$cur"
                        fi
                        ;;
                esac
                ;;
            esac
        fi
        ;;
    config)
        if [[ -z "$subcmd" ]]; then
            COMPREPLY=($(compgen -W "show edit" -- "$cur"))
        fi
        ;;
    completions)
        if [[ "$cur" == -* ]]; then
            COMPREPLY=($(compgen -W "--install" -- "$cur"))
        else
            COMPREPLY=($(compgen -W "bash zsh fish" -- "$cur"))
        fi
        ;;
    esac
}

complete -o default -F _equip equip
"#;

pub const FISH_SCRIPT: &str = r#"# Equip — agent skill manager
# Generated by: equip completions fish

# Helpers for dynamic completions
function __equip_sources
    equip _complete sources 2>/dev/null
end

function __equip_agents
    equip _complete agents 2>/dev/null
end

function __equip_skills
    equip _complete skills 2>/dev/null
end

function __equip_plugins
    equip _complete plugins 2>/dev/null
end

function __equip_kits
    equip _complete kits 2>/dev/null
end

function __equip_needs_command
    set -l cmd (commandline -opc)
    test (count $cmd) -eq 1
end

function __equip_using_command
    set -l cmd (commandline -opc)
    test (count $cmd) -gt 1; and test "$cmd[2]" = "$argv[1]"
end

function __equip_using_subcommand
    set -l cmd (commandline -opc)
    test (count $cmd) -gt 2; and test "$cmd[2]" = "$argv[1]"; and test "$cmd[3]" = "$argv[2]"
end

# Global flags
complete -c equip -l dry-run -s n -d 'Preview changes without writing'
complete -c equip -l verbose -s v -d 'Show detailed output'
complete -c equip -l quiet -s q -d 'Suppress output'
complete -c equip -l json -d 'Output as JSON'
complete -c equip -l config -r -d 'Override config file path'
complete -c equip -l help -s h -d 'Show help'
complete -c equip -l version -d 'Show version'

# Top-level commands
complete -c equip -f -n __equip_needs_command -a init -d 'Initialize equip configuration'
complete -c equip -f -n __equip_needs_command -a add -d 'Add a skill source'
complete -c equip -f -n __equip_needs_command -a list -d 'List skills'
complete -c equip -f -n __equip_needs_command -a remove -d 'Remove local skills or a source'
complete -c equip -f -n __equip_needs_command -a collect -d 'Collect skills from an agent back to the library'
complete -c equip -f -n __equip_needs_command -a status -d 'Show current install state'
complete -c equip -f -n __equip_needs_command -a source -d 'Manage sources'
complete -c equip -f -n __equip_needs_command -a kit -d 'Manage skill kits'
complete -c equip -f -n __equip_needs_command -a agent -d 'Manage agents'
complete -c equip -f -n __equip_needs_command -a config -d 'View or edit configuration'
complete -c equip -f -n __equip_needs_command -a completions -d 'Generate shell completions'

# add (no -f: allow filesystem completion for local paths)
complete -c equip -n '__equip_using_command add' -l source -r -d 'Override source name'
complete -c equip -n '__equip_using_command add' -l plugin -r -d 'Override plugin name'
complete -c equip -n '__equip_using_command add' -l skill -r -d 'Override skill name'
complete -c equip -n '__equip_using_command add' -l ref -r -d 'Pin to git ref'
complete -c equip -n '__equip_using_command add' -l symlink -d 'Symlink local source'
complete -c equip -n '__equip_using_command add' -l copy -d 'Copy local source'

# list
complete -c equip -f -n '__equip_using_command list' -l external -d 'List sources instead'

# remove
complete -c equip -f -n '__equip_using_command remove' -l force -d 'Force removal'
complete -c equip -f -n '__equip_using_command remove' -a '(__equip_skills) (__equip_sources)'

# collect
complete -c equip -f -n '__equip_using_command collect' -l agent -r -a '(__equip_agents)' -d 'Agent'
complete -c equip -f -n '__equip_using_command collect' -l adopt -d 'Adopt into the local source'
complete -c equip -f -n '__equip_using_command collect' -l force -s f -d 'Auto-adopt all'
complete -c equip -f -n '__equip_using_command collect' -l interactive -s i -d 'Interactive skill selection'
complete -c equip -f -n '__equip_using_command collect' -a '(__equip_skills)'

# source
complete -c equip -f -n '__equip_using_command source' -a add -d 'Add a skill source'
complete -c equip -f -n '__equip_using_command source' -a list -d 'List configured sources'
complete -c equip -f -n '__equip_using_command source' -a remove -d 'Remove a source'
complete -c equip -f -n '__equip_using_command source' -a update -d 'Update sources from remote'

complete -c equip -n '__equip_using_subcommand source add' -l source -r -d 'Override source name'
complete -c equip -n '__equip_using_subcommand source add' -l plugin -r -d 'Override plugin name'
complete -c equip -n '__equip_using_subcommand source add' -l skill -r -d 'Override skill name'
complete -c equip -n '__equip_using_subcommand source add' -l ref -r -d 'Pin to git ref'
complete -c equip -n '__equip_using_subcommand source add' -l symlink -d 'Symlink local source'
complete -c equip -n '__equip_using_subcommand source add' -l copy -d 'Copy local source'
complete -c equip -f -n '__equip_using_subcommand source remove' -l force -d 'Force removal'
complete -c equip -f -n '__equip_using_subcommand source remove' -a '(__equip_sources)'
complete -c equip -f -n '__equip_using_subcommand source update' -l ref -r -d 'Switch to ref'
complete -c equip -f -n '__equip_using_subcommand source update' -a '(__equip_sources)'

# kit subcommands
complete -c equip -f -n '__equip_using_command kit' -a create -d 'Create a new kit'
complete -c equip -f -n '__equip_using_command kit' -a delete -d 'Delete a kit'
complete -c equip -f -n '__equip_using_command kit' -a list -d 'List kits'
complete -c equip -f -n '__equip_using_command kit' -a show -d 'Show kit details'
complete -c equip -f -n '__equip_using_command kit' -a add -d 'Add skills to a kit'
complete -c equip -f -n '__equip_using_command kit' -a drop -d 'Remove skills from a kit'

complete -c equip -f -n '__equip_using_subcommand kit delete' -l force -d 'Force delete'
complete -c equip -f -n '__equip_using_subcommand kit delete' -a '(__equip_kits)'
complete -c equip -f -n '__equip_using_subcommand kit show' -a '(__equip_kits)'
complete -c equip -f -n '__equip_using_subcommand kit add' -a '(__equip_kits) (__equip_skills)'
complete -c equip -f -n '__equip_using_subcommand kit drop' -a '(__equip_kits) (__equip_skills)'

# agent subcommands
complete -c equip -f -n '__equip_using_command agent' -a add -d 'Register a new agent'
complete -c equip -f -n '__equip_using_command agent' -a remove -d 'Unregister an agent'
complete -c equip -f -n '__equip_using_command agent' -a list -d 'Show all agents'
complete -c equip -f -n '__equip_using_command agent' -a show -d 'Show agent details'
complete -c equip -f -n '__equip_using_command agent' -a detect -d 'Auto-discover agents'
complete -c equip -f -n '__equip_using_command agent' -a equip -d 'Equip skills to agents'
complete -c equip -f -n '__equip_using_command agent' -a unequip -d 'Unequip skills from agents'
complete -c equip -f -n '__equip_using_command agent' -a collect -d 'Collect edited skills back'

complete -c equip -f -n '__equip_using_subcommand agent add' -l name -r -d 'Agent name'
complete -c equip -f -n '__equip_using_subcommand agent add' -l scope -r -a 'machine repo' -d 'Scope'
complete -c equip -f -n '__equip_using_subcommand agent add' -l sync -r -a 'auto explicit' -d 'Sync mode'
complete -c equip -f -n '__equip_using_subcommand agent add' -a 'claude codex cursor'
complete -c equip -f -n '__equip_using_subcommand agent remove' -l force -d 'Required for removal'
complete -c equip -f -n '__equip_using_subcommand agent remove' -a '(__equip_agents)'
complete -c equip -f -n '__equip_using_subcommand agent show' -a '(__equip_agents)'
complete -c equip -f -n '__equip_using_subcommand agent detect' -l force -d 'Auto-add'
complete -c equip -f -n '__equip_using_subcommand agent equip' -l agent -s a -r -a '(__equip_agents)' -d 'Agent'
complete -c equip -f -n '__equip_using_subcommand agent equip' -l all -d 'All configured skills'
complete -c equip -f -n '__equip_using_subcommand agent equip' -l kit -s k -r -a '(__equip_kits)' -d 'Kit to equip'
complete -c equip -f -n '__equip_using_subcommand agent equip' -l save-kit -s s -r -d 'Save selection as kit'
complete -c equip -f -n '__equip_using_subcommand agent equip' -l force -s f -d 'Overwrite without prompting'
complete -c equip -f -n '__equip_using_subcommand agent equip' -l interactive -s i -d 'Interactive conflict resolution'
complete -c equip -f -n '__equip_using_subcommand agent equip' -a '(__equip_skills)'
complete -c equip -f -n '__equip_using_subcommand agent unequip' -l agent -s a -r -a '(__equip_agents)' -d 'Agent'
complete -c equip -f -n '__equip_using_subcommand agent unequip' -l all -d 'All equipped skills'
complete -c equip -f -n '__equip_using_subcommand agent unequip' -l kit -s k -r -a '(__equip_kits)' -d 'Kit to unequip'
complete -c equip -f -n '__equip_using_subcommand agent unequip' -l force -s f -d 'Force unequip'
complete -c equip -f -n '__equip_using_subcommand agent unequip' -a '(__equip_skills)'
complete -c equip -f -n '__equip_using_subcommand agent collect' -l agent -r -a '(__equip_agents)' -d 'Agent'
complete -c equip -f -n '__equip_using_subcommand agent collect' -l adopt -d 'Adopt into the local source'
complete -c equip -f -n '__equip_using_subcommand agent collect' -l force -s f -d 'Auto-adopt all'
complete -c equip -f -n '__equip_using_subcommand agent collect' -l interactive -s i -d 'Interactive skill selection'
complete -c equip -f -n '__equip_using_subcommand agent collect' -a '(__equip_skills)'

# config subcommands
complete -c equip -f -n '__equip_using_command config' -a show -d 'Display configuration'
complete -c equip -f -n '__equip_using_command config' -a edit -d 'Open in editor'

# completions
complete -c equip -f -n '__equip_using_command completions' -l install -d 'Install to shell config'
complete -c equip -f -n '__equip_using_command completions' -a 'bash zsh fish'
"#;

/// Install completions for zsh.
pub fn install_zsh(quiet: bool) -> Result<PathBuf> {
    let home = dirs::home_dir().context("cannot determine home directory")?;

    // Prefer oh-my-zsh completions dir if it exists
    let omz_dir = home.join(".oh-my-zsh/completions");
    let (dest, extra) = if omz_dir.is_dir() {
        (omz_dir.join("_equip"), None)
    } else {
        let zfunc = home.join(".zfunc");
        fs::create_dir_all(&zfunc)
            .with_context(|| format!("failed to create {}", zfunc.display()))?;

        let needs_fpath = {
            let zshrc = home.join(".zshrc");
            if let Ok(content) = fs::read_to_string(&zshrc) {
                !content.contains(".zfunc")
            } else {
                true
            }
        };

        let hint = if needs_fpath {
            Some(format!(
                "\n{}  Add to {} (before compinit):\n\n    {}\n    {}",
                "Note:".yellow().bold(),
                "~/.zshrc".bold(),
                "fpath=(~/.zfunc $fpath)",
                "autoload -Uz compinit && compinit",
            ))
        } else {
            None
        };

        (zfunc.join("_equip"), hint)
    };

    fs::write(&dest, ZSH_SCRIPT).with_context(|| format!("failed to write {}", dest.display()))?;

    if !quiet {
        println!(
            "{} Installed zsh completions to {}",
            "✓".green(),
            dest.display().to_string().bold()
        );
        if let Some(hint) = extra {
            println!("{}", hint);
        }
        println!("\nRestart your shell or run: {}", "exec zsh".bold());
    }

    Ok(dest)
}

/// Install completions for bash.
pub fn install_bash(quiet: bool) -> Result<PathBuf> {
    let home = dirs::home_dir().context("cannot determine home directory")?;
    let comp_dir = home.join(".local/share/bash-completion/completions");
    fs::create_dir_all(&comp_dir)
        .with_context(|| format!("failed to create {}", comp_dir.display()))?;

    let dest = comp_dir.join("equip");
    fs::write(&dest, BASH_SCRIPT).with_context(|| format!("failed to write {}", dest.display()))?;

    if !quiet {
        println!(
            "{} Installed bash completions to {}",
            "✓".green(),
            dest.display().to_string().bold()
        );
        println!(
            "\nRestart your shell or run: {}",
            format!("source {}", dest.display()).bold()
        );
    }

    Ok(dest)
}

/// Install completions for fish.
pub fn install_fish(quiet: bool) -> Result<PathBuf> {
    let home = dirs::home_dir().context("cannot determine home directory")?;
    let comp_dir = home.join(".config/fish/completions");
    fs::create_dir_all(&comp_dir)
        .with_context(|| format!("failed to create {}", comp_dir.display()))?;

    let dest = comp_dir.join("equip.fish");
    fs::write(&dest, FISH_SCRIPT).with_context(|| format!("failed to write {}", dest.display()))?;

    if !quiet {
        println!(
            "{} Installed fish completions to {}",
            "✓".green(),
            dest.display().to_string().bold()
        );
        println!("\nCompletions are available in new fish sessions.");
    }

    Ok(dest)
}
